services:
  jellyfin:
    image: jellyfin/jellyfin
    hostname: jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - type: bind
        source: ~/jellyfin/media
        target: /media
    restart: 'unless-stopped'
  caddy:
    image: caddy:2.11.2-alpine
    hostname: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"
      - "80:80"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.4.0
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ~/seerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
      - 8112:8112
      - 7878:7878
      - 8989:8989
    volumes:
      - /mnt/docker/vpn_media/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WG_ADDR}
      - SERVER_COUNTRIES=France,Switzerland
      - TZ=Europe/Zurich
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /mnt/docker/vpn_media/radarr/data:/config
      - type: bind
        source: ~/jellyfin/media
        target: /media
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /mnt/docker/vpn_media/sonarr/data:/config
      - type: bind
        source: ~/jellyfin/media
        target: /media
    restart: unless-stopped

volumes:
  caddy_data:

